/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.11.0
 *
 * Project: 'example-project.debug_GCC+STM32C542RCT6' 
 * Target:  'debug_GCC+STM32C542RCT6' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* STMicroelectronics::Device:STM32CubeMX2 Config:RCC@2.1.0 */
#define USE_EXTERNAL_ENV


#endif /* PRE_INCLUDE_GLOBAL_H */
